name: overwrite

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        options:
          - hutao
          - deployment
        description: 'hutao / deployment'
        required: false
        default: 'hutao'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: python main.py ${{ github.event.inputs.project }}
      env:
        OVERWRITE_TOKEN: ${{ secrets.OVERWRITE_TOKEN }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        CDN_TOKEN: ${{ secrets.CDN_TOKEN }}
